production:
  solr:
    hostname: http://ec2-50-112-195-52.us-west-2.compute.amazonaws.com
    port: 8983
    path: /solr
    log_level: WARNING

staging:
  solr:
    hostname: http://ec2-50-112-195-52.us-west-2.compute.amazonaws.com
    port: 8983
    path: /solr
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
